"""Type stubs for the compiled pps extension module.

Mirrors python/bindings.cpp. Keep in sync when the bindings change.
A .pyi file is never executed, so this does not affect runtime.
"""

from collections.abc import Iterator
from typing import overload

Real = float
RealList = list
SizeType = int

class Polynomial:
	def __init__(self, coeffs: list[float] = ...) -> None: ...
	def __len__(self) -> int: ...
	def __getitem__(self, i: int) -> float: ...
	def __setitem__(self, i: int, v: float) -> None: ...
	def __iter__(self) -> Iterator[float]: ...
	def to_list(self) -> list[float]: ...
	def __add__(self, other: Polynomial) -> Polynomial: ...
	def __sub__(self, other: Polynomial) -> Polynomial: ...
	@overload
	def __mul__(self, other: Polynomial) -> Polynomial: ...
	@overload
	def __mul__(self, other: float) -> Polynomial: ...
	def __rmul__(self, other: float) -> Polynomial: ...
	def __truediv__(self, other: float) -> Polynomial: ...
	def __neg__(self) -> Polynomial: ...
	def __repr__(self) -> str: ...
	def __str__(self) -> str: ...

class PolynomialDivision:
	quotient: Polynomial
	remainder: float

def evaluate(x: float, poly: Polynomial | list[float]) -> float: ...
def horner_division(
	a: Polynomial | list[float],
	b: Polynomial | list[float],
) -> PolynomialDivision: ...
def chebyshev_nodes(lower: float, upper: float, num_nodes: int) -> list[float]: ...
def display_polynomial_evaluation(x: float, poly: Polynomial | list[float]) -> None: ...
def display_horner_division(
	a: Polynomial | list[float],
	b: Polynomial | list[float],
) -> None: ...
def display_chebyshev_nodes(lower: float, upper: float, num_nodes: int) -> None: ...
